pipeline {
  agent {
      label 'maven'
  }
  stages {
    stage('Build App') {
      steps {
        sh "mvn package "
      }
    }
    stage('Create Image Builder') {
      when {
        expression {
          openshift.withCluster() {
            return !openshift.selector("bc", "users-informix-poc").exists();
          }
        }
      }
      steps {
        script {
          openshift.withCluster() {
            openshift.newBuild("--name=users-informix-poc", "--image-stream=openshift/redhat-openjdk18-openshift:1.2")
          }
        }
      }
    }
//    stage('Build Image') {
//      steps {
//        script {
//          openshift.withCluster() {
//            openshift.selector("bc", "crtstservici").startBuild("--from-file=target/crtstservici.jar", "--wait")
//          }
//        }
//      }
//    }
//    stage('Promote to DEV') {
//      steps {
//        script {
//          openshift.withCluster() {
//            openshift.tag("crtstservici:latest", "crtstservici:dev")
//          }
//        }
//      }
//    }
//    stage('Create DEV') {
//      when {
//        expression {
//          openshift.withCluster() {
//            return !openshift.selector('dc', 'crtstservici-dev').exists()
//          }
//        }
//      }
//      steps {
//        script {
//          openshift.withCluster() {
//            openshift.newApp("crtstservici:latest", "--name=crtstservici-dev").narrow('svc').expose()
//          }
//        }
//      }
//    }
//    stage('Promote STAGE') {
//      steps {
//        script {
//          openshift.withCluster() {
//            openshift.tag("crtstservici:dev", "crtstservici:stage")
//          }
//        }
//      }
//    }
//    stage('Create STAGE') {
//      when {
//        expression {
//          openshift.withCluster() {
//            return !openshift.selector('dc', 'crtstservici-stage').exists()
//          }
//        }
//      }
//      steps {
//        script {
//          openshift.withCluster() {
//            openshift.newApp("crtstservici:stage", "--name=crtstservici-stage").narrow('svc').expose()
//          }
//        }
//      }
//    }
  }
}
