node('maven')  
        {
         stage 'BuildDev'
         openshiftBuild(namespace: 'poc-slarq', buildConfig: 'users-informix-poc', showBuildLogs: 'true')
         stage 'VerifyBuild'
         openshiftVerifyBuild(namespace: 'poc-slarq', bldCfg) 
         stage 'DeployTest'
         openshiftDeploy(namespace: 'poc-slarq-test', deploymentConfig: 'users-informix-poc', showBuildLogs: 'true')
         stage 'VerifyDeploymentTest'
         openshiftVerifyDeployment(namespace: 'poc-slarq-test', deploymentConfig: 'users-informix-poc')
         stage('Promote to Prod?') {
                steps {
                  timeout(time:15, unit:'MINUTES') {
                      input message: "Promote to Prod?", ok: "Promote"
                  }
                  openshiftDeploy(namespace: 'poc-slarq-prod', deploymentConfig: 'users-informix-poc', showBuildLogs: 'true')
                }}
         //stage 'Scale'   
         //openshiftScale(namespace: 'simplepipeline', deploymentConfig: 'nodetest', replicaCount: '4')
        
