node('maven')  
        {
         stage 'BuildDev'
         openshiftBuild(namespace: 'poc-slarq', buildConfig: 'users-informix-poc', showBuildLogs: 'true')
         stage 'DeployTest'
         openshiftDeploy(namespace: 'poc-slarq-test ', deploymentConfig: 'users-informix-poc', showBuildLogs: 'true')
         //stage 'Scale'   
         //openshiftScale(namespace: 'simplepipeline', deploymentConfig: 'nodetest', replicaCount: '4')
       } 
